[package]
name = "libisyntax-rs"
version = "0.1.0"
edition = "2024"
links = "libisyntax"
build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]
image = "0.25.8"
thiserror = "2"

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1.54"
